In [20]:
from numpy import array
from numpy import argmax
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [30]:
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
data2 = ['A','B','C']
values = array(data)
values2 = array(data2)
print(values)
print(values2)

#join example
a = pd.DataFrame(values)
b = pd.DataFrame(values2)
b=a.join(b,lsuffix='_', rsuffix='_')
b.head()

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
['A' 'B' 'C']


0_   0_
0  cold    A
1  cold    B
2  warm    C
3  cold  NaN
4   hot  NaN

In [16]:
# integer encode
label_encoder = LabelEncoder()
label_encoder2 = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
integer_encoded2 = label_encoder2.fit_transform(values2)
print(integer_encoded)
print(integer_encoded2)

decoded=label_encoder.inverse_transform(integer_encoded)
decoded2=label_encoder2.inverse_transform(integer_encoded2)
print(decoded)
print(decoded2)

[0 0 2 0 1 1 2 0 2 1]
[0 1 2]
['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
['A' 'B' 'C']


In [17]:
# binary encode
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]


In [18]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[:, :])])
print(inverted)

['cold']


In [19]:
def dummyEncode(df):
        columnsToEncode = list(df.select_dtypes(include=['category','object']))
        le = LabelEncoder()
        for feature in columnsToEncode:
            try:
                df[feature] = le.fit_transform(df[feature])
            except:
                print('Error encoding '+feature)
        return df